f/models.py
from f import db, login_manager
from flask import current_app
from flask_login import UserMixin


@login_manager.user_loader   ##basic login manager decorator 
def load_user(user_id):		## to get th user ID
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):      ##User class that will create an entry in database consisting of (username,email,password)
    id = db.Column(db.Integer, primary_key=True) ## id is set to be the primary key
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120),unique=True, nullable=False )
    password = db.Column(db.String(60), nullable=False)

    def __repr__(self):
        return f"User('{self.username}')"

f/main/forms.py
##

f/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField ##different types of field that form will contains
from wtforms.validators import DataRequired, Length, Email, ValidationError ## data required so that it is compulsory to fill that field
from flask_login import current_user ## to get  the current user
from f.models import User## users that was created in models

class RegistrationForm(FlaskForm): ## registeration form 
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign Up')

    def validate_username(self, username): ## if username validation is unsuccessfull it will return Validation Error 
        user = User.query.filter_by(username=username.data).first() ## it will check the entered username exists or not
        if user:
            raise ValidationError('username exist')

    def validate_email(self, email): ## if username validation is unsuccessfull it will return Validation Error 
        user = User.query.filter_by(email=email.data).first() ## it will check the entered email exists or not
        if user:
            raise ValidationError('email exist')


class LoginForm(FlaskForm): ## login form 
    username = StringField('Username',
                        validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class UpdateAccountForm(FlaskForm): ## to update account details
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Update')

    def validate_username(self, username): ## validate useraname 
        ## same as the above mentioned validate_username in Registeration Form we can use that also with the decorator
        ##having extra functionality fron checking the current user condition
        if username.data != current_user.username:      
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken')

    def validate_email(self, email):
        ## same as the above mentioned validate_email in Registeration Form we can use that also with the decorator
        ##having extra functionality fron checking the current user condition
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken')

f/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from f.config import Config
db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
def create_app(config_class=Config): ## funtion to create flask app 
	app = Flask(__name__)
	app.config['SECRET_KEY']=Config.SECRET_KEY
	app.config['SQLALCHEMY_DATABASE_URI']=Config.SQLALCHEMY_DATABASE_URI
	db.init_app(app)
	bcrypt.init_app(app)
	login_manager.init_app(app) 
	from f.users.routes import users  
	from f.main.routes import main
	app.register_blueprint(users) ## blue prints from the users 
	app.register_blueprint(main) ##blue prints from the main
	return app

f/main/__init__.py
##

f/main/routes.py
from flask import Blueprint, render_template, request
main=Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

f/users/__init__.py
##

f/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from f import db, bcrypt
from f.models import User
from f.users.forms import RegistrationForm, LoginForm, UpdateAccountForm

users=Blueprint('users',__name__)

@users.route("/register", methods=['GET', 'POST'])
def register():   ## routes to register
    if current_user.is_authenticated:       ## to check the user authenciated already then redirect it to home page or can be set to login page
        return redirect(url_for('users.home'))
    form = RegistrationForm()        ## RegistrationForm imported from flask 
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') ##password is hashed using the bcrypt
        user = User(username=form.username.data, email=form.email.data, password=hashed_password) ##user data will be saving in the database Usinf the User from model file
        db.session.add(user) 
        db.session.commit()
        flash('now log in')
        return redirect(url_for('users.login')) ##if the entry that was filled in the form is validated it gets return back to the login page for login
    return render_template('register.html', title='Register', form=form) ##otherwise the register page is reloaded 

@users.route("/login", methods=['GET', 'POST'])
def login(): ##routes to login page
    if current_user.is_authenticated: 
        return redirect(url_for('users.account')) ##if the current users is already authenciated then it will be redirected to his/her account page
    form = LoginForm() ##LoginForm imported form Flask
    if form.validate_on_submit(): ##if the user from is validated 
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data): ##password is checked using the chech_password_hash function form bcrypt
            login_user(user)
            next_page = request.args.get('next') ## to get the nest request 
            return redirect(next_page) if next_page else redirect(url_for('users.account'))
        else:
            flash('Login Unsuccess')
    return render_template('login.html', title='Login', form=form) ## if the login is unsucess due to some reason it is reloaded back to login page


@users.route("/logout")
def logout():## route to logout
    logout_user() ##imported form flask
    return redirect(url_for('users.login')) ##redireted to login page

@users.route("/delete",methods=['GET', 'POST'])
@login_required
def delete(): ##to delete the current user
    db.session.delete(current_user) 
    db.session.commit()
    return redirect(url_for('users.login')) ##after deleting the current user it will be redirected to the login page

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account(): ## route to user account page conating information to update the account
    form = UpdateAccountForm() ##imported form flask
    if form.validate_on_submit(): ## it updates the current user data to submitted data obtained from form
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)

f/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div>
        <form method="POST" action=""enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset>
                <div><!-- this division tag conatins form for username field -->
                    {{ form.username.label() }}
                    {% if form.username.errors %}
                        {{ form.username() }}
                        <div>
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username() }}
                    {% endif %}
                </div>
                <div><!-- this division tag conatins form for email field -->
                    {{ form.email.label() }}
                    {% if form.email.errors %}
                        {{ form.email() }}
                        <div>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email() }}
                    {% endif %}
                </div>
            </fieldset>
            <div>  
                {{ form.submit() }}
            </div>
        </form>
        <a href="{{url_for('users.logout')}}">log out</a>
        <a href="{{url_for('users.delete')}}">delete</a><!-- to delete the current user that will call delete from routes -->
    </div>
{% endblock content %}

f/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <a href="{{url_for('users.register')}}">register</a>
    <a href="{{url_for('users.login')}}">signin</a>
{% endblock %}

f/templates/layout.html
<!DOCTYPE html><!-- a basic bootstrap template -->
<html>
<head>
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title></title>
</head>
<body>
        <div class="container">
          {% block content %}{% endblock %} <!-- block that will get continue in differnt pages -->
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

f/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset >
                <legend >Log In</legend>
                <div >
                    {{ form.username.label() }}
                    {% if form.username.errors %}
                        {{ form.username() }}
                        <div>
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username() }}
                    {% endif %}
                </div>
                <div >
                    {{ form.password.label() }}
                    {% if form.password.errors %}
                        {{ form.password() }}
                        <div>
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password() }}
                    {% endif %}
                </div>
            </fieldset>
            <div >
                {{ form.submit() }}
            </div>
        </form>
    </div>
    <div>
          <a href="{{url_for('users.register')}}">register</a>
    </div>
{% endblock content %}

f/templates/register.html
{% extends "layout.html" %}
{% block content %} <!-- continude from layout-->
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend>sign up</legend>
                <div> <!-- this division tag conatins form for username field -->
                    {{ form.username.label() }} <!-- label to add extra classes-->

                    {% if form.username.errors %}
                        {{ form.username() }}
                        <div>
                            {% for error in form.username.errors %}<!-- for loop for errors in the username field -->
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username() }}
                    {% endif %}
                </div>
                <div><!-- this division tag conatins form for email field -->
                    {{ form.email.label() }}  <!-- label to add extra classes-->
                    {% if form.email.errors %}
                        {{ form.email() }}
                        <div>
                            {% for error in form.email.errors %}<!-- for loop for errors in the email field -->
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email() }}
                    {% endif %}
                </div>
                <div><!-- this division tag conatins form for password field -->
                    {{ form.password.label() }}  <!-- label to add extra classes-->
                    {% if form.password.errors %}
                        {{ form.password() }}
                        <div>
                            {% for error in form.password.errors %}<!-- for loop for errors in the password field -->
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password() }}
                    {% endif %}
                </div>
            </fieldset>
            <div>
                {{ form.submit() }}
            </div>
        </form>
    </div>
    <div>
        <small>
            <a href="{{ url_for('users.login') }}">Sign In</a> <!-- redirection if the user want to login instead -->
        </small>
    </div>
{% endblock content %}